// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_talent.proto

#ifndef PROTOBUF_db_5ftalent_2eproto__INCLUDED
#define PROTOBUF_db_5ftalent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_db_5ftalent_2eproto();
void protobuf_AssignDesc_db_5ftalent_2eproto();
void protobuf_ShutdownFile_db_5ftalent_2eproto();

class ProtoDbTalentPoint;
class ProtoDbTalentInfo;
class AllTalentInfo;

// ===================================================================

class ProtoDbTalentPoint : public ::google::protobuf::Message {
 public:
  ProtoDbTalentPoint();
  virtual ~ProtoDbTalentPoint();

  ProtoDbTalentPoint(const ProtoDbTalentPoint& from);

  inline ProtoDbTalentPoint& operator=(const ProtoDbTalentPoint& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDbTalentPoint& default_instance();

  void Swap(ProtoDbTalentPoint* other);

  // implements Message ----------------------------------------------

  ProtoDbTalentPoint* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoDbTalentPoint& from);
  void MergeFrom(const ProtoDbTalentPoint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // required int32 stage = 2;
  inline bool has_stage() const;
  inline void clear_stage();
  static const int kStageFieldNumber = 2;
  inline ::google::protobuf::int32 stage() const;
  inline void set_stage(::google::protobuf::int32 value);

  // required int32 point = 3;
  inline bool has_point() const;
  inline void clear_point();
  static const int kPointFieldNumber = 3;
  inline ::google::protobuf::int32 point() const;
  inline void set_point(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.message.ProtoDbTalentPoint)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_stage();
  inline void clear_has_stage();
  inline void set_has_point();
  inline void clear_has_point();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 stage_;
  ::google::protobuf::int32 point_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_db_5ftalent_2eproto();
  friend void protobuf_AssignDesc_db_5ftalent_2eproto();
  friend void protobuf_ShutdownFile_db_5ftalent_2eproto();

  void InitAsDefaultInstance();
  static ProtoDbTalentPoint* default_instance_;
};
// -------------------------------------------------------------------

class ProtoDbTalentInfo : public ::google::protobuf::Message {
 public:
  ProtoDbTalentInfo();
  virtual ~ProtoDbTalentInfo();

  ProtoDbTalentInfo(const ProtoDbTalentInfo& from);

  inline ProtoDbTalentInfo& operator=(const ProtoDbTalentInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDbTalentInfo& default_instance();

  void Swap(ProtoDbTalentInfo* other);

  // implements Message ----------------------------------------------

  ProtoDbTalentInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoDbTalentInfo& from);
  void MergeFrom(const ProtoDbTalentInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 tabs = 1;
  inline bool has_tabs() const;
  inline void clear_tabs();
  static const int kTabsFieldNumber = 1;
  inline ::google::protobuf::int32 tabs() const;
  inline void set_tabs(::google::protobuf::int32 value);

  // required int32 point = 2;
  inline bool has_point() const;
  inline void clear_point();
  static const int kPointFieldNumber = 2;
  inline ::google::protobuf::int32 point() const;
  inline void set_point(::google::protobuf::int32 value);

  // required int32 resetNum = 3;
  inline bool has_resetnum() const;
  inline void clear_resetnum();
  static const int kResetNumFieldNumber = 3;
  inline ::google::protobuf::int32 resetnum() const;
  inline void set_resetnum(::google::protobuf::int32 value);

  // repeated int32 talentList = 4;
  inline int talentlist_size() const;
  inline void clear_talentlist();
  static const int kTalentListFieldNumber = 4;
  inline ::google::protobuf::int32 talentlist(int index) const;
  inline void set_talentlist(int index, ::google::protobuf::int32 value);
  inline void add_talentlist(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      talentlist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_talentlist();

  // repeated .proto.message.ProtoDbTalentPoint pointList = 5;
  inline int pointlist_size() const;
  inline void clear_pointlist();
  static const int kPointListFieldNumber = 5;
  inline const ::proto::message::ProtoDbTalentPoint& pointlist(int index) const;
  inline ::proto::message::ProtoDbTalentPoint* mutable_pointlist(int index);
  inline ::proto::message::ProtoDbTalentPoint* add_pointlist();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentPoint >&
      pointlist() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentPoint >*
      mutable_pointlist();

  // @@protoc_insertion_point(class_scope:proto.message.ProtoDbTalentInfo)
 private:
  inline void set_has_tabs();
  inline void clear_has_tabs();
  inline void set_has_point();
  inline void clear_has_point();
  inline void set_has_resetnum();
  inline void clear_has_resetnum();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 tabs_;
  ::google::protobuf::int32 point_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > talentlist_;
  ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentPoint > pointlist_;
  ::google::protobuf::int32 resetnum_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_db_5ftalent_2eproto();
  friend void protobuf_AssignDesc_db_5ftalent_2eproto();
  friend void protobuf_ShutdownFile_db_5ftalent_2eproto();

  void InitAsDefaultInstance();
  static ProtoDbTalentInfo* default_instance_;
};
// -------------------------------------------------------------------

class AllTalentInfo : public ::google::protobuf::Message {
 public:
  AllTalentInfo();
  virtual ~AllTalentInfo();

  AllTalentInfo(const AllTalentInfo& from);

  inline AllTalentInfo& operator=(const AllTalentInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AllTalentInfo& default_instance();

  void Swap(AllTalentInfo* other);

  // implements Message ----------------------------------------------

  AllTalentInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AllTalentInfo& from);
  void MergeFrom(const AllTalentInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 talentUnLockList = 1;
  inline int talentunlocklist_size() const;
  inline void clear_talentunlocklist();
  static const int kTalentUnLockListFieldNumber = 1;
  inline ::google::protobuf::int32 talentunlocklist(int index) const;
  inline void set_talentunlocklist(int index, ::google::protobuf::int32 value);
  inline void add_talentunlocklist(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      talentunlocklist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_talentunlocklist();

  // repeated .proto.message.ProtoDbTalentInfo tabsList = 2;
  inline int tabslist_size() const;
  inline void clear_tabslist();
  static const int kTabsListFieldNumber = 2;
  inline const ::proto::message::ProtoDbTalentInfo& tabslist(int index) const;
  inline ::proto::message::ProtoDbTalentInfo* mutable_tabslist(int index);
  inline ::proto::message::ProtoDbTalentInfo* add_tabslist();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentInfo >&
      tabslist() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentInfo >*
      mutable_tabslist();

  // @@protoc_insertion_point(class_scope:proto.message.AllTalentInfo)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > talentunlocklist_;
  ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentInfo > tabslist_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_db_5ftalent_2eproto();
  friend void protobuf_AssignDesc_db_5ftalent_2eproto();
  friend void protobuf_ShutdownFile_db_5ftalent_2eproto();

  void InitAsDefaultInstance();
  static AllTalentInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoDbTalentPoint

// required int32 type = 1;
inline bool ProtoDbTalentPoint::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDbTalentPoint::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDbTalentPoint::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDbTalentPoint::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 ProtoDbTalentPoint::type() const {
  return type_;
}
inline void ProtoDbTalentPoint::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// required int32 stage = 2;
inline bool ProtoDbTalentPoint::has_stage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoDbTalentPoint::set_has_stage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoDbTalentPoint::clear_has_stage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoDbTalentPoint::clear_stage() {
  stage_ = 0;
  clear_has_stage();
}
inline ::google::protobuf::int32 ProtoDbTalentPoint::stage() const {
  return stage_;
}
inline void ProtoDbTalentPoint::set_stage(::google::protobuf::int32 value) {
  set_has_stage();
  stage_ = value;
}

// required int32 point = 3;
inline bool ProtoDbTalentPoint::has_point() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoDbTalentPoint::set_has_point() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoDbTalentPoint::clear_has_point() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoDbTalentPoint::clear_point() {
  point_ = 0;
  clear_has_point();
}
inline ::google::protobuf::int32 ProtoDbTalentPoint::point() const {
  return point_;
}
inline void ProtoDbTalentPoint::set_point(::google::protobuf::int32 value) {
  set_has_point();
  point_ = value;
}

// -------------------------------------------------------------------

// ProtoDbTalentInfo

// required int32 tabs = 1;
inline bool ProtoDbTalentInfo::has_tabs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDbTalentInfo::set_has_tabs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDbTalentInfo::clear_has_tabs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDbTalentInfo::clear_tabs() {
  tabs_ = 0;
  clear_has_tabs();
}
inline ::google::protobuf::int32 ProtoDbTalentInfo::tabs() const {
  return tabs_;
}
inline void ProtoDbTalentInfo::set_tabs(::google::protobuf::int32 value) {
  set_has_tabs();
  tabs_ = value;
}

// required int32 point = 2;
inline bool ProtoDbTalentInfo::has_point() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoDbTalentInfo::set_has_point() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoDbTalentInfo::clear_has_point() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoDbTalentInfo::clear_point() {
  point_ = 0;
  clear_has_point();
}
inline ::google::protobuf::int32 ProtoDbTalentInfo::point() const {
  return point_;
}
inline void ProtoDbTalentInfo::set_point(::google::protobuf::int32 value) {
  set_has_point();
  point_ = value;
}

// required int32 resetNum = 3;
inline bool ProtoDbTalentInfo::has_resetnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoDbTalentInfo::set_has_resetnum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoDbTalentInfo::clear_has_resetnum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoDbTalentInfo::clear_resetnum() {
  resetnum_ = 0;
  clear_has_resetnum();
}
inline ::google::protobuf::int32 ProtoDbTalentInfo::resetnum() const {
  return resetnum_;
}
inline void ProtoDbTalentInfo::set_resetnum(::google::protobuf::int32 value) {
  set_has_resetnum();
  resetnum_ = value;
}

// repeated int32 talentList = 4;
inline int ProtoDbTalentInfo::talentlist_size() const {
  return talentlist_.size();
}
inline void ProtoDbTalentInfo::clear_talentlist() {
  talentlist_.Clear();
}
inline ::google::protobuf::int32 ProtoDbTalentInfo::talentlist(int index) const {
  return talentlist_.Get(index);
}
inline void ProtoDbTalentInfo::set_talentlist(int index, ::google::protobuf::int32 value) {
  talentlist_.Set(index, value);
}
inline void ProtoDbTalentInfo::add_talentlist(::google::protobuf::int32 value) {
  talentlist_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ProtoDbTalentInfo::talentlist() const {
  return talentlist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ProtoDbTalentInfo::mutable_talentlist() {
  return &talentlist_;
}

// repeated .proto.message.ProtoDbTalentPoint pointList = 5;
inline int ProtoDbTalentInfo::pointlist_size() const {
  return pointlist_.size();
}
inline void ProtoDbTalentInfo::clear_pointlist() {
  pointlist_.Clear();
}
inline const ::proto::message::ProtoDbTalentPoint& ProtoDbTalentInfo::pointlist(int index) const {
  return pointlist_.Get(index);
}
inline ::proto::message::ProtoDbTalentPoint* ProtoDbTalentInfo::mutable_pointlist(int index) {
  return pointlist_.Mutable(index);
}
inline ::proto::message::ProtoDbTalentPoint* ProtoDbTalentInfo::add_pointlist() {
  return pointlist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentPoint >&
ProtoDbTalentInfo::pointlist() const {
  return pointlist_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentPoint >*
ProtoDbTalentInfo::mutable_pointlist() {
  return &pointlist_;
}

// -------------------------------------------------------------------

// AllTalentInfo

// repeated int32 talentUnLockList = 1;
inline int AllTalentInfo::talentunlocklist_size() const {
  return talentunlocklist_.size();
}
inline void AllTalentInfo::clear_talentunlocklist() {
  talentunlocklist_.Clear();
}
inline ::google::protobuf::int32 AllTalentInfo::talentunlocklist(int index) const {
  return talentunlocklist_.Get(index);
}
inline void AllTalentInfo::set_talentunlocklist(int index, ::google::protobuf::int32 value) {
  talentunlocklist_.Set(index, value);
}
inline void AllTalentInfo::add_talentunlocklist(::google::protobuf::int32 value) {
  talentunlocklist_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
AllTalentInfo::talentunlocklist() const {
  return talentunlocklist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
AllTalentInfo::mutable_talentunlocklist() {
  return &talentunlocklist_;
}

// repeated .proto.message.ProtoDbTalentInfo tabsList = 2;
inline int AllTalentInfo::tabslist_size() const {
  return tabslist_.size();
}
inline void AllTalentInfo::clear_tabslist() {
  tabslist_.Clear();
}
inline const ::proto::message::ProtoDbTalentInfo& AllTalentInfo::tabslist(int index) const {
  return tabslist_.Get(index);
}
inline ::proto::message::ProtoDbTalentInfo* AllTalentInfo::mutable_tabslist(int index) {
  return tabslist_.Mutable(index);
}
inline ::proto::message::ProtoDbTalentInfo* AllTalentInfo::add_tabslist() {
  return tabslist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentInfo >&
AllTalentInfo::tabslist() const {
  return tabslist_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoDbTalentInfo >*
AllTalentInfo::mutable_tabslist() {
  return &tabslist_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_db_5ftalent_2eproto__INCLUDED
