// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awaken.proto

#ifndef PROTOBUF_awaken_2eproto__INCLUDED
#define PROTOBUF_awaken_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace proto {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_awaken_2eproto();
void protobuf_AssignDesc_awaken_2eproto();
void protobuf_ShutdownFile_awaken_2eproto();

class ProtoAwakenTalentInfo;
class ProtoAwakenCellInfo;
class ProtoAwakenAllCellInfo;
class Awaken_CS_FroceTransEnd;
class Awaken_SC_FroceTransEnd;
class Awaken_CS_GetAwakenInfo;
class Awaken_SC_GetAwakenInfo;
class Awaken_CS_Upgrade;
class Awaken_SC_Upgrade;
class Awaken_CS_ResetTalent;
class Awaken_SC_ResetTalent;
class Awaken_CS_UpgTalent;
class Awaken_SC_UpgTalent;
class Awaken_CS_UpgSkill;
class Awaken_SC_UpgSkill;
class Awaken_CS_Transform;
class Awaken_SC_Transform;
class Awaken_CS_SkillOpen;
class Awaken_SC_SkillOpen;

// ===================================================================

class ProtoAwakenTalentInfo : public ::google::protobuf::Message {
 public:
  ProtoAwakenTalentInfo();
  virtual ~ProtoAwakenTalentInfo();

  ProtoAwakenTalentInfo(const ProtoAwakenTalentInfo& from);

  inline ProtoAwakenTalentInfo& operator=(const ProtoAwakenTalentInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoAwakenTalentInfo& default_instance();

  void Swap(ProtoAwakenTalentInfo* other);

  // implements Message ----------------------------------------------

  ProtoAwakenTalentInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoAwakenTalentInfo& from);
  void MergeFrom(const ProtoAwakenTalentInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 talentId = 1;
  inline bool has_talentid() const;
  inline void clear_talentid();
  static const int kTalentIdFieldNumber = 1;
  inline ::google::protobuf::uint32 talentid() const;
  inline void set_talentid(::google::protobuf::uint32 value);

  // optional uint32 talentType = 2;
  inline bool has_talenttype() const;
  inline void clear_talenttype();
  static const int kTalentTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 talenttype() const;
  inline void set_talenttype(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.message.ProtoAwakenTalentInfo)
 private:
  inline void set_has_talentid();
  inline void clear_has_talentid();
  inline void set_has_talenttype();
  inline void clear_has_talenttype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 talentid_;
  ::google::protobuf::uint32 talenttype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static ProtoAwakenTalentInfo* default_instance_;
};
// -------------------------------------------------------------------

class ProtoAwakenCellInfo : public ::google::protobuf::Message {
 public:
  ProtoAwakenCellInfo();
  virtual ~ProtoAwakenCellInfo();

  ProtoAwakenCellInfo(const ProtoAwakenCellInfo& from);

  inline ProtoAwakenCellInfo& operator=(const ProtoAwakenCellInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoAwakenCellInfo& default_instance();

  void Swap(ProtoAwakenCellInfo* other);

  // implements Message ----------------------------------------------

  ProtoAwakenCellInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoAwakenCellInfo& from);
  void MergeFrom(const ProtoAwakenCellInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 awakenId = 1;
  inline bool has_awakenid() const;
  inline void clear_awakenid();
  static const int kAwakenIdFieldNumber = 1;
  inline ::google::protobuf::uint32 awakenid() const;
  inline void set_awakenid(::google::protobuf::uint32 value);

  // optional uint32 strLv = 2;
  inline bool has_strlv() const;
  inline void clear_strlv();
  static const int kStrLvFieldNumber = 2;
  inline ::google::protobuf::uint32 strlv() const;
  inline void set_strlv(::google::protobuf::uint32 value);

  // optional uint32 luckyValue = 3;
  inline bool has_luckyvalue() const;
  inline void clear_luckyvalue();
  static const int kLuckyValueFieldNumber = 3;
  inline ::google::protobuf::uint32 luckyvalue() const;
  inline void set_luckyvalue(::google::protobuf::uint32 value);

  // optional uint32 nTalentPoint = 4;
  inline bool has_ntalentpoint() const;
  inline void clear_ntalentpoint();
  static const int kNTalentPointFieldNumber = 4;
  inline ::google::protobuf::uint32 ntalentpoint() const;
  inline void set_ntalentpoint(::google::protobuf::uint32 value);

  // optional uint32 UsedTalentPoint = 5;
  inline bool has_usedtalentpoint() const;
  inline void clear_usedtalentpoint();
  static const int kUsedTalentPointFieldNumber = 5;
  inline ::google::protobuf::uint32 usedtalentpoint() const;
  inline void set_usedtalentpoint(::google::protobuf::uint32 value);

  // repeated .proto.message.ProtoAwakenTalentInfo telentInfo = 6;
  inline int telentinfo_size() const;
  inline void clear_telentinfo();
  static const int kTelentInfoFieldNumber = 6;
  inline const ::proto::message::ProtoAwakenTalentInfo& telentinfo(int index) const;
  inline ::proto::message::ProtoAwakenTalentInfo* mutable_telentinfo(int index);
  inline ::proto::message::ProtoAwakenTalentInfo* add_telentinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoAwakenTalentInfo >&
      telentinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoAwakenTalentInfo >*
      mutable_telentinfo();

  // repeated int32 nSkill = 7;
  inline int nskill_size() const;
  inline void clear_nskill();
  static const int kNSkillFieldNumber = 7;
  inline ::google::protobuf::int32 nskill(int index) const;
  inline void set_nskill(int index, ::google::protobuf::int32 value);
  inline void add_nskill(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      nskill() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_nskill();

  // repeated uint32 skillbooks = 8;
  inline int skillbooks_size() const;
  inline void clear_skillbooks();
  static const int kSkillbooksFieldNumber = 8;
  inline ::google::protobuf::uint32 skillbooks(int index) const;
  inline void set_skillbooks(int index, ::google::protobuf::uint32 value);
  inline void add_skillbooks(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      skillbooks() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_skillbooks();

  // @@protoc_insertion_point(class_scope:proto.message.ProtoAwakenCellInfo)
 private:
  inline void set_has_awakenid();
  inline void clear_has_awakenid();
  inline void set_has_strlv();
  inline void clear_has_strlv();
  inline void set_has_luckyvalue();
  inline void clear_has_luckyvalue();
  inline void set_has_ntalentpoint();
  inline void clear_has_ntalentpoint();
  inline void set_has_usedtalentpoint();
  inline void clear_has_usedtalentpoint();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 awakenid_;
  ::google::protobuf::uint32 strlv_;
  ::google::protobuf::uint32 luckyvalue_;
  ::google::protobuf::uint32 ntalentpoint_;
  ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoAwakenTalentInfo > telentinfo_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > nskill_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > skillbooks_;
  ::google::protobuf::uint32 usedtalentpoint_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static ProtoAwakenCellInfo* default_instance_;
};
// -------------------------------------------------------------------

class ProtoAwakenAllCellInfo : public ::google::protobuf::Message {
 public:
  ProtoAwakenAllCellInfo();
  virtual ~ProtoAwakenAllCellInfo();

  ProtoAwakenAllCellInfo(const ProtoAwakenAllCellInfo& from);

  inline ProtoAwakenAllCellInfo& operator=(const ProtoAwakenAllCellInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoAwakenAllCellInfo& default_instance();

  void Swap(ProtoAwakenAllCellInfo* other);

  // implements Message ----------------------------------------------

  ProtoAwakenAllCellInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoAwakenAllCellInfo& from);
  void MergeFrom(const ProtoAwakenAllCellInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .proto.message.ProtoAwakenCellInfo allInfo = 1;
  inline bool has_allinfo() const;
  inline void clear_allinfo();
  static const int kAllInfoFieldNumber = 1;
  inline const ::proto::message::ProtoAwakenCellInfo& allinfo() const;
  inline ::proto::message::ProtoAwakenCellInfo* mutable_allinfo();
  inline ::proto::message::ProtoAwakenCellInfo* release_allinfo();
  inline void set_allocated_allinfo(::proto::message::ProtoAwakenCellInfo* allinfo);

  // @@protoc_insertion_point(class_scope:proto.message.ProtoAwakenAllCellInfo)
 private:
  inline void set_has_allinfo();
  inline void clear_has_allinfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::proto::message::ProtoAwakenCellInfo* allinfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static ProtoAwakenAllCellInfo* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_FroceTransEnd : public ::google::protobuf::Message {
 public:
  Awaken_CS_FroceTransEnd();
  virtual ~Awaken_CS_FroceTransEnd();

  Awaken_CS_FroceTransEnd(const Awaken_CS_FroceTransEnd& from);

  inline Awaken_CS_FroceTransEnd& operator=(const Awaken_CS_FroceTransEnd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_FroceTransEnd& default_instance();

  void Swap(Awaken_CS_FroceTransEnd* other);

  // implements Message ----------------------------------------------

  Awaken_CS_FroceTransEnd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_FroceTransEnd& from);
  void MergeFrom(const Awaken_CS_FroceTransEnd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_FroceTransEnd)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_FroceTransEnd* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_FroceTransEnd : public ::google::protobuf::Message {
 public:
  Awaken_SC_FroceTransEnd();
  virtual ~Awaken_SC_FroceTransEnd();

  Awaken_SC_FroceTransEnd(const Awaken_SC_FroceTransEnd& from);

  inline Awaken_SC_FroceTransEnd& operator=(const Awaken_SC_FroceTransEnd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_FroceTransEnd& default_instance();

  void Swap(Awaken_SC_FroceTransEnd* other);

  // implements Message ----------------------------------------------

  Awaken_SC_FroceTransEnd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_FroceTransEnd& from);
  void MergeFrom(const Awaken_SC_FroceTransEnd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_FroceTransEnd)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_FroceTransEnd* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_GetAwakenInfo : public ::google::protobuf::Message {
 public:
  Awaken_CS_GetAwakenInfo();
  virtual ~Awaken_CS_GetAwakenInfo();

  Awaken_CS_GetAwakenInfo(const Awaken_CS_GetAwakenInfo& from);

  inline Awaken_CS_GetAwakenInfo& operator=(const Awaken_CS_GetAwakenInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_GetAwakenInfo& default_instance();

  void Swap(Awaken_CS_GetAwakenInfo* other);

  // implements Message ----------------------------------------------

  Awaken_CS_GetAwakenInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_GetAwakenInfo& from);
  void MergeFrom(const Awaken_CS_GetAwakenInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_GetAwakenInfo)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_GetAwakenInfo* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_GetAwakenInfo : public ::google::protobuf::Message {
 public:
  Awaken_SC_GetAwakenInfo();
  virtual ~Awaken_SC_GetAwakenInfo();

  Awaken_SC_GetAwakenInfo(const Awaken_SC_GetAwakenInfo& from);

  inline Awaken_SC_GetAwakenInfo& operator=(const Awaken_SC_GetAwakenInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_GetAwakenInfo& default_instance();

  void Swap(Awaken_SC_GetAwakenInfo* other);

  // implements Message ----------------------------------------------

  Awaken_SC_GetAwakenInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_GetAwakenInfo& from);
  void MergeFrom(const Awaken_SC_GetAwakenInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .proto.message.ProtoAwakenCellInfo infoList = 1;
  inline bool has_infolist() const;
  inline void clear_infolist();
  static const int kInfoListFieldNumber = 1;
  inline const ::proto::message::ProtoAwakenCellInfo& infolist() const;
  inline ::proto::message::ProtoAwakenCellInfo* mutable_infolist();
  inline ::proto::message::ProtoAwakenCellInfo* release_infolist();
  inline void set_allocated_infolist(::proto::message::ProtoAwakenCellInfo* infolist);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_GetAwakenInfo)
 private:
  inline void set_has_infolist();
  inline void clear_has_infolist();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::proto::message::ProtoAwakenCellInfo* infolist_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_GetAwakenInfo* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_Upgrade : public ::google::protobuf::Message {
 public:
  Awaken_CS_Upgrade();
  virtual ~Awaken_CS_Upgrade();

  Awaken_CS_Upgrade(const Awaken_CS_Upgrade& from);

  inline Awaken_CS_Upgrade& operator=(const Awaken_CS_Upgrade& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_Upgrade& default_instance();

  void Swap(Awaken_CS_Upgrade* other);

  // implements Message ----------------------------------------------

  Awaken_CS_Upgrade* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_Upgrade& from);
  void MergeFrom(const Awaken_CS_Upgrade& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_Upgrade)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_Upgrade* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_Upgrade : public ::google::protobuf::Message {
 public:
  Awaken_SC_Upgrade();
  virtual ~Awaken_SC_Upgrade();

  Awaken_SC_Upgrade(const Awaken_SC_Upgrade& from);

  inline Awaken_SC_Upgrade& operator=(const Awaken_SC_Upgrade& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_Upgrade& default_instance();

  void Swap(Awaken_SC_Upgrade* other);

  // implements Message ----------------------------------------------

  Awaken_SC_Upgrade* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_Upgrade& from);
  void MergeFrom(const Awaken_SC_Upgrade& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::uint32 ret() const;
  inline void set_ret(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_Upgrade)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_Upgrade* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_ResetTalent : public ::google::protobuf::Message {
 public:
  Awaken_CS_ResetTalent();
  virtual ~Awaken_CS_ResetTalent();

  Awaken_CS_ResetTalent(const Awaken_CS_ResetTalent& from);

  inline Awaken_CS_ResetTalent& operator=(const Awaken_CS_ResetTalent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_ResetTalent& default_instance();

  void Swap(Awaken_CS_ResetTalent* other);

  // implements Message ----------------------------------------------

  Awaken_CS_ResetTalent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_ResetTalent& from);
  void MergeFrom(const Awaken_CS_ResetTalent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_ResetTalent)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_ResetTalent* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_ResetTalent : public ::google::protobuf::Message {
 public:
  Awaken_SC_ResetTalent();
  virtual ~Awaken_SC_ResetTalent();

  Awaken_SC_ResetTalent(const Awaken_SC_ResetTalent& from);

  inline Awaken_SC_ResetTalent& operator=(const Awaken_SC_ResetTalent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_ResetTalent& default_instance();

  void Swap(Awaken_SC_ResetTalent* other);

  // implements Message ----------------------------------------------

  Awaken_SC_ResetTalent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_ResetTalent& from);
  void MergeFrom(const Awaken_SC_ResetTalent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::uint32 ret() const;
  inline void set_ret(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_ResetTalent)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_ResetTalent* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_UpgTalent : public ::google::protobuf::Message {
 public:
  Awaken_CS_UpgTalent();
  virtual ~Awaken_CS_UpgTalent();

  Awaken_CS_UpgTalent(const Awaken_CS_UpgTalent& from);

  inline Awaken_CS_UpgTalent& operator=(const Awaken_CS_UpgTalent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_UpgTalent& default_instance();

  void Swap(Awaken_CS_UpgTalent* other);

  // implements Message ----------------------------------------------

  Awaken_CS_UpgTalent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_UpgTalent& from);
  void MergeFrom(const Awaken_CS_UpgTalent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 talentType = 1;
  inline bool has_talenttype() const;
  inline void clear_talenttype();
  static const int kTalentTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 talenttype() const;
  inline void set_talenttype(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_UpgTalent)
 private:
  inline void set_has_talenttype();
  inline void clear_has_talenttype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 talenttype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_UpgTalent* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_UpgTalent : public ::google::protobuf::Message {
 public:
  Awaken_SC_UpgTalent();
  virtual ~Awaken_SC_UpgTalent();

  Awaken_SC_UpgTalent(const Awaken_SC_UpgTalent& from);

  inline Awaken_SC_UpgTalent& operator=(const Awaken_SC_UpgTalent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_UpgTalent& default_instance();

  void Swap(Awaken_SC_UpgTalent* other);

  // implements Message ----------------------------------------------

  Awaken_SC_UpgTalent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_UpgTalent& from);
  void MergeFrom(const Awaken_SC_UpgTalent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::uint32 ret() const;
  inline void set_ret(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_UpgTalent)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_UpgTalent* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_UpgSkill : public ::google::protobuf::Message {
 public:
  Awaken_CS_UpgSkill();
  virtual ~Awaken_CS_UpgSkill();

  Awaken_CS_UpgSkill(const Awaken_CS_UpgSkill& from);

  inline Awaken_CS_UpgSkill& operator=(const Awaken_CS_UpgSkill& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_UpgSkill& default_instance();

  void Swap(Awaken_CS_UpgSkill* other);

  // implements Message ----------------------------------------------

  Awaken_CS_UpgSkill* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_UpgSkill& from);
  void MergeFrom(const Awaken_CS_UpgSkill& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 skillid = 1;
  inline bool has_skillid() const;
  inline void clear_skillid();
  static const int kSkillidFieldNumber = 1;
  inline ::google::protobuf::int32 skillid() const;
  inline void set_skillid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_UpgSkill)
 private:
  inline void set_has_skillid();
  inline void clear_has_skillid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 skillid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_UpgSkill* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_UpgSkill : public ::google::protobuf::Message {
 public:
  Awaken_SC_UpgSkill();
  virtual ~Awaken_SC_UpgSkill();

  Awaken_SC_UpgSkill(const Awaken_SC_UpgSkill& from);

  inline Awaken_SC_UpgSkill& operator=(const Awaken_SC_UpgSkill& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_UpgSkill& default_instance();

  void Swap(Awaken_SC_UpgSkill* other);

  // implements Message ----------------------------------------------

  Awaken_SC_UpgSkill* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_UpgSkill& from);
  void MergeFrom(const Awaken_SC_UpgSkill& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_UpgSkill)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_UpgSkill* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_Transform : public ::google::protobuf::Message {
 public:
  Awaken_CS_Transform();
  virtual ~Awaken_CS_Transform();

  Awaken_CS_Transform(const Awaken_CS_Transform& from);

  inline Awaken_CS_Transform& operator=(const Awaken_CS_Transform& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_Transform& default_instance();

  void Swap(Awaken_CS_Transform* other);

  // implements Message ----------------------------------------------

  Awaken_CS_Transform* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_Transform& from);
  void MergeFrom(const Awaken_CS_Transform& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_Transform)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_Transform* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_Transform : public ::google::protobuf::Message {
 public:
  Awaken_SC_Transform();
  virtual ~Awaken_SC_Transform();

  Awaken_SC_Transform(const Awaken_SC_Transform& from);

  inline Awaken_SC_Transform& operator=(const Awaken_SC_Transform& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_Transform& default_instance();

  void Swap(Awaken_SC_Transform* other);

  // implements Message ----------------------------------------------

  Awaken_SC_Transform* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_Transform& from);
  void MergeFrom(const Awaken_SC_Transform& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // optional uint32 awakenId = 2;
  inline bool has_awakenid() const;
  inline void clear_awakenid();
  static const int kAwakenIdFieldNumber = 2;
  inline ::google::protobuf::uint32 awakenid() const;
  inline void set_awakenid(::google::protobuf::uint32 value);

  // optional bool status = 3;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 3;
  inline bool status() const;
  inline void set_status(bool value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_Transform)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();
  inline void set_has_awakenid();
  inline void clear_has_awakenid();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;
  ::google::protobuf::uint32 awakenid_;
  bool status_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_Transform* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_CS_SkillOpen : public ::google::protobuf::Message {
 public:
  Awaken_CS_SkillOpen();
  virtual ~Awaken_CS_SkillOpen();

  Awaken_CS_SkillOpen(const Awaken_CS_SkillOpen& from);

  inline Awaken_CS_SkillOpen& operator=(const Awaken_CS_SkillOpen& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_CS_SkillOpen& default_instance();

  void Swap(Awaken_CS_SkillOpen* other);

  // implements Message ----------------------------------------------

  Awaken_CS_SkillOpen* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_CS_SkillOpen& from);
  void MergeFrom(const Awaken_CS_SkillOpen& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 bookItemId = 1;
  inline bool has_bookitemid() const;
  inline void clear_bookitemid();
  static const int kBookItemIdFieldNumber = 1;
  inline ::google::protobuf::uint32 bookitemid() const;
  inline void set_bookitemid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_CS_SkillOpen)
 private:
  inline void set_has_bookitemid();
  inline void clear_has_bookitemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 bookitemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_CS_SkillOpen* default_instance_;
};
// -------------------------------------------------------------------

class Awaken_SC_SkillOpen : public ::google::protobuf::Message {
 public:
  Awaken_SC_SkillOpen();
  virtual ~Awaken_SC_SkillOpen();

  Awaken_SC_SkillOpen(const Awaken_SC_SkillOpen& from);

  inline Awaken_SC_SkillOpen& operator=(const Awaken_SC_SkillOpen& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Awaken_SC_SkillOpen& default_instance();

  void Swap(Awaken_SC_SkillOpen* other);

  // implements Message ----------------------------------------------

  Awaken_SC_SkillOpen* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Awaken_SC_SkillOpen& from);
  void MergeFrom(const Awaken_SC_SkillOpen& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.message.Awaken_SC_SkillOpen)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_awaken_2eproto();
  friend void protobuf_AssignDesc_awaken_2eproto();
  friend void protobuf_ShutdownFile_awaken_2eproto();

  void InitAsDefaultInstance();
  static Awaken_SC_SkillOpen* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoAwakenTalentInfo

// optional uint32 talentId = 1;
inline bool ProtoAwakenTalentInfo::has_talentid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoAwakenTalentInfo::set_has_talentid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoAwakenTalentInfo::clear_has_talentid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoAwakenTalentInfo::clear_talentid() {
  talentid_ = 0u;
  clear_has_talentid();
}
inline ::google::protobuf::uint32 ProtoAwakenTalentInfo::talentid() const {
  return talentid_;
}
inline void ProtoAwakenTalentInfo::set_talentid(::google::protobuf::uint32 value) {
  set_has_talentid();
  talentid_ = value;
}

// optional uint32 talentType = 2;
inline bool ProtoAwakenTalentInfo::has_talenttype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoAwakenTalentInfo::set_has_talenttype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoAwakenTalentInfo::clear_has_talenttype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoAwakenTalentInfo::clear_talenttype() {
  talenttype_ = 0u;
  clear_has_talenttype();
}
inline ::google::protobuf::uint32 ProtoAwakenTalentInfo::talenttype() const {
  return talenttype_;
}
inline void ProtoAwakenTalentInfo::set_talenttype(::google::protobuf::uint32 value) {
  set_has_talenttype();
  talenttype_ = value;
}

// -------------------------------------------------------------------

// ProtoAwakenCellInfo

// optional uint32 awakenId = 1;
inline bool ProtoAwakenCellInfo::has_awakenid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoAwakenCellInfo::set_has_awakenid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoAwakenCellInfo::clear_has_awakenid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoAwakenCellInfo::clear_awakenid() {
  awakenid_ = 0u;
  clear_has_awakenid();
}
inline ::google::protobuf::uint32 ProtoAwakenCellInfo::awakenid() const {
  return awakenid_;
}
inline void ProtoAwakenCellInfo::set_awakenid(::google::protobuf::uint32 value) {
  set_has_awakenid();
  awakenid_ = value;
}

// optional uint32 strLv = 2;
inline bool ProtoAwakenCellInfo::has_strlv() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoAwakenCellInfo::set_has_strlv() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoAwakenCellInfo::clear_has_strlv() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoAwakenCellInfo::clear_strlv() {
  strlv_ = 0u;
  clear_has_strlv();
}
inline ::google::protobuf::uint32 ProtoAwakenCellInfo::strlv() const {
  return strlv_;
}
inline void ProtoAwakenCellInfo::set_strlv(::google::protobuf::uint32 value) {
  set_has_strlv();
  strlv_ = value;
}

// optional uint32 luckyValue = 3;
inline bool ProtoAwakenCellInfo::has_luckyvalue() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoAwakenCellInfo::set_has_luckyvalue() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoAwakenCellInfo::clear_has_luckyvalue() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoAwakenCellInfo::clear_luckyvalue() {
  luckyvalue_ = 0u;
  clear_has_luckyvalue();
}
inline ::google::protobuf::uint32 ProtoAwakenCellInfo::luckyvalue() const {
  return luckyvalue_;
}
inline void ProtoAwakenCellInfo::set_luckyvalue(::google::protobuf::uint32 value) {
  set_has_luckyvalue();
  luckyvalue_ = value;
}

// optional uint32 nTalentPoint = 4;
inline bool ProtoAwakenCellInfo::has_ntalentpoint() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtoAwakenCellInfo::set_has_ntalentpoint() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProtoAwakenCellInfo::clear_has_ntalentpoint() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProtoAwakenCellInfo::clear_ntalentpoint() {
  ntalentpoint_ = 0u;
  clear_has_ntalentpoint();
}
inline ::google::protobuf::uint32 ProtoAwakenCellInfo::ntalentpoint() const {
  return ntalentpoint_;
}
inline void ProtoAwakenCellInfo::set_ntalentpoint(::google::protobuf::uint32 value) {
  set_has_ntalentpoint();
  ntalentpoint_ = value;
}

// optional uint32 UsedTalentPoint = 5;
inline bool ProtoAwakenCellInfo::has_usedtalentpoint() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProtoAwakenCellInfo::set_has_usedtalentpoint() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProtoAwakenCellInfo::clear_has_usedtalentpoint() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProtoAwakenCellInfo::clear_usedtalentpoint() {
  usedtalentpoint_ = 0u;
  clear_has_usedtalentpoint();
}
inline ::google::protobuf::uint32 ProtoAwakenCellInfo::usedtalentpoint() const {
  return usedtalentpoint_;
}
inline void ProtoAwakenCellInfo::set_usedtalentpoint(::google::protobuf::uint32 value) {
  set_has_usedtalentpoint();
  usedtalentpoint_ = value;
}

// repeated .proto.message.ProtoAwakenTalentInfo telentInfo = 6;
inline int ProtoAwakenCellInfo::telentinfo_size() const {
  return telentinfo_.size();
}
inline void ProtoAwakenCellInfo::clear_telentinfo() {
  telentinfo_.Clear();
}
inline const ::proto::message::ProtoAwakenTalentInfo& ProtoAwakenCellInfo::telentinfo(int index) const {
  return telentinfo_.Get(index);
}
inline ::proto::message::ProtoAwakenTalentInfo* ProtoAwakenCellInfo::mutable_telentinfo(int index) {
  return telentinfo_.Mutable(index);
}
inline ::proto::message::ProtoAwakenTalentInfo* ProtoAwakenCellInfo::add_telentinfo() {
  return telentinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoAwakenTalentInfo >&
ProtoAwakenCellInfo::telentinfo() const {
  return telentinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::message::ProtoAwakenTalentInfo >*
ProtoAwakenCellInfo::mutable_telentinfo() {
  return &telentinfo_;
}

// repeated int32 nSkill = 7;
inline int ProtoAwakenCellInfo::nskill_size() const {
  return nskill_.size();
}
inline void ProtoAwakenCellInfo::clear_nskill() {
  nskill_.Clear();
}
inline ::google::protobuf::int32 ProtoAwakenCellInfo::nskill(int index) const {
  return nskill_.Get(index);
}
inline void ProtoAwakenCellInfo::set_nskill(int index, ::google::protobuf::int32 value) {
  nskill_.Set(index, value);
}
inline void ProtoAwakenCellInfo::add_nskill(::google::protobuf::int32 value) {
  nskill_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ProtoAwakenCellInfo::nskill() const {
  return nskill_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ProtoAwakenCellInfo::mutable_nskill() {
  return &nskill_;
}

// repeated uint32 skillbooks = 8;
inline int ProtoAwakenCellInfo::skillbooks_size() const {
  return skillbooks_.size();
}
inline void ProtoAwakenCellInfo::clear_skillbooks() {
  skillbooks_.Clear();
}
inline ::google::protobuf::uint32 ProtoAwakenCellInfo::skillbooks(int index) const {
  return skillbooks_.Get(index);
}
inline void ProtoAwakenCellInfo::set_skillbooks(int index, ::google::protobuf::uint32 value) {
  skillbooks_.Set(index, value);
}
inline void ProtoAwakenCellInfo::add_skillbooks(::google::protobuf::uint32 value) {
  skillbooks_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ProtoAwakenCellInfo::skillbooks() const {
  return skillbooks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ProtoAwakenCellInfo::mutable_skillbooks() {
  return &skillbooks_;
}

// -------------------------------------------------------------------

// ProtoAwakenAllCellInfo

// optional .proto.message.ProtoAwakenCellInfo allInfo = 1;
inline bool ProtoAwakenAllCellInfo::has_allinfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoAwakenAllCellInfo::set_has_allinfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoAwakenAllCellInfo::clear_has_allinfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoAwakenAllCellInfo::clear_allinfo() {
  if (allinfo_ != NULL) allinfo_->::proto::message::ProtoAwakenCellInfo::Clear();
  clear_has_allinfo();
}
inline const ::proto::message::ProtoAwakenCellInfo& ProtoAwakenAllCellInfo::allinfo() const {
  return allinfo_ != NULL ? *allinfo_ : *default_instance_->allinfo_;
}
inline ::proto::message::ProtoAwakenCellInfo* ProtoAwakenAllCellInfo::mutable_allinfo() {
  set_has_allinfo();
  if (allinfo_ == NULL) allinfo_ = new ::proto::message::ProtoAwakenCellInfo;
  return allinfo_;
}
inline ::proto::message::ProtoAwakenCellInfo* ProtoAwakenAllCellInfo::release_allinfo() {
  clear_has_allinfo();
  ::proto::message::ProtoAwakenCellInfo* temp = allinfo_;
  allinfo_ = NULL;
  return temp;
}
inline void ProtoAwakenAllCellInfo::set_allocated_allinfo(::proto::message::ProtoAwakenCellInfo* allinfo) {
  delete allinfo_;
  allinfo_ = allinfo;
  if (allinfo) {
    set_has_allinfo();
  } else {
    clear_has_allinfo();
  }
}

// -------------------------------------------------------------------

// Awaken_CS_FroceTransEnd

// -------------------------------------------------------------------

// Awaken_SC_FroceTransEnd

// optional int32 ret = 1;
inline bool Awaken_SC_FroceTransEnd::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_FroceTransEnd::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_FroceTransEnd::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_FroceTransEnd::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 Awaken_SC_FroceTransEnd::ret() const {
  return ret_;
}
inline void Awaken_SC_FroceTransEnd::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// Awaken_CS_GetAwakenInfo

// -------------------------------------------------------------------

// Awaken_SC_GetAwakenInfo

// optional .proto.message.ProtoAwakenCellInfo infoList = 1;
inline bool Awaken_SC_GetAwakenInfo::has_infolist() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_GetAwakenInfo::set_has_infolist() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_GetAwakenInfo::clear_has_infolist() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_GetAwakenInfo::clear_infolist() {
  if (infolist_ != NULL) infolist_->::proto::message::ProtoAwakenCellInfo::Clear();
  clear_has_infolist();
}
inline const ::proto::message::ProtoAwakenCellInfo& Awaken_SC_GetAwakenInfo::infolist() const {
  return infolist_ != NULL ? *infolist_ : *default_instance_->infolist_;
}
inline ::proto::message::ProtoAwakenCellInfo* Awaken_SC_GetAwakenInfo::mutable_infolist() {
  set_has_infolist();
  if (infolist_ == NULL) infolist_ = new ::proto::message::ProtoAwakenCellInfo;
  return infolist_;
}
inline ::proto::message::ProtoAwakenCellInfo* Awaken_SC_GetAwakenInfo::release_infolist() {
  clear_has_infolist();
  ::proto::message::ProtoAwakenCellInfo* temp = infolist_;
  infolist_ = NULL;
  return temp;
}
inline void Awaken_SC_GetAwakenInfo::set_allocated_infolist(::proto::message::ProtoAwakenCellInfo* infolist) {
  delete infolist_;
  infolist_ = infolist;
  if (infolist) {
    set_has_infolist();
  } else {
    clear_has_infolist();
  }
}

// -------------------------------------------------------------------

// Awaken_CS_Upgrade

// -------------------------------------------------------------------

// Awaken_SC_Upgrade

// optional uint32 ret = 1;
inline bool Awaken_SC_Upgrade::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_Upgrade::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_Upgrade::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_Upgrade::clear_ret() {
  ret_ = 0u;
  clear_has_ret();
}
inline ::google::protobuf::uint32 Awaken_SC_Upgrade::ret() const {
  return ret_;
}
inline void Awaken_SC_Upgrade::set_ret(::google::protobuf::uint32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// Awaken_CS_ResetTalent

// -------------------------------------------------------------------

// Awaken_SC_ResetTalent

// optional uint32 ret = 1;
inline bool Awaken_SC_ResetTalent::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_ResetTalent::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_ResetTalent::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_ResetTalent::clear_ret() {
  ret_ = 0u;
  clear_has_ret();
}
inline ::google::protobuf::uint32 Awaken_SC_ResetTalent::ret() const {
  return ret_;
}
inline void Awaken_SC_ResetTalent::set_ret(::google::protobuf::uint32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// Awaken_CS_UpgTalent

// optional uint32 talentType = 1;
inline bool Awaken_CS_UpgTalent::has_talenttype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_CS_UpgTalent::set_has_talenttype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_CS_UpgTalent::clear_has_talenttype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_CS_UpgTalent::clear_talenttype() {
  talenttype_ = 0u;
  clear_has_talenttype();
}
inline ::google::protobuf::uint32 Awaken_CS_UpgTalent::talenttype() const {
  return talenttype_;
}
inline void Awaken_CS_UpgTalent::set_talenttype(::google::protobuf::uint32 value) {
  set_has_talenttype();
  talenttype_ = value;
}

// -------------------------------------------------------------------

// Awaken_SC_UpgTalent

// optional uint32 ret = 1;
inline bool Awaken_SC_UpgTalent::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_UpgTalent::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_UpgTalent::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_UpgTalent::clear_ret() {
  ret_ = 0u;
  clear_has_ret();
}
inline ::google::protobuf::uint32 Awaken_SC_UpgTalent::ret() const {
  return ret_;
}
inline void Awaken_SC_UpgTalent::set_ret(::google::protobuf::uint32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// Awaken_CS_UpgSkill

// required int32 skillid = 1;
inline bool Awaken_CS_UpgSkill::has_skillid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_CS_UpgSkill::set_has_skillid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_CS_UpgSkill::clear_has_skillid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_CS_UpgSkill::clear_skillid() {
  skillid_ = 0;
  clear_has_skillid();
}
inline ::google::protobuf::int32 Awaken_CS_UpgSkill::skillid() const {
  return skillid_;
}
inline void Awaken_CS_UpgSkill::set_skillid(::google::protobuf::int32 value) {
  set_has_skillid();
  skillid_ = value;
}

// -------------------------------------------------------------------

// Awaken_SC_UpgSkill

// required int32 ret = 1;
inline bool Awaken_SC_UpgSkill::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_UpgSkill::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_UpgSkill::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_UpgSkill::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 Awaken_SC_UpgSkill::ret() const {
  return ret_;
}
inline void Awaken_SC_UpgSkill::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// Awaken_CS_Transform

// -------------------------------------------------------------------

// Awaken_SC_Transform

// required int32 ret = 1;
inline bool Awaken_SC_Transform::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_Transform::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_Transform::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_Transform::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 Awaken_SC_Transform::ret() const {
  return ret_;
}
inline void Awaken_SC_Transform::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// optional uint32 awakenId = 2;
inline bool Awaken_SC_Transform::has_awakenid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Awaken_SC_Transform::set_has_awakenid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Awaken_SC_Transform::clear_has_awakenid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Awaken_SC_Transform::clear_awakenid() {
  awakenid_ = 0u;
  clear_has_awakenid();
}
inline ::google::protobuf::uint32 Awaken_SC_Transform::awakenid() const {
  return awakenid_;
}
inline void Awaken_SC_Transform::set_awakenid(::google::protobuf::uint32 value) {
  set_has_awakenid();
  awakenid_ = value;
}

// optional bool status = 3;
inline bool Awaken_SC_Transform::has_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Awaken_SC_Transform::set_has_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Awaken_SC_Transform::clear_has_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Awaken_SC_Transform::clear_status() {
  status_ = false;
  clear_has_status();
}
inline bool Awaken_SC_Transform::status() const {
  return status_;
}
inline void Awaken_SC_Transform::set_status(bool value) {
  set_has_status();
  status_ = value;
}

// -------------------------------------------------------------------

// Awaken_CS_SkillOpen

// optional uint32 bookItemId = 1;
inline bool Awaken_CS_SkillOpen::has_bookitemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_CS_SkillOpen::set_has_bookitemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_CS_SkillOpen::clear_has_bookitemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_CS_SkillOpen::clear_bookitemid() {
  bookitemid_ = 0u;
  clear_has_bookitemid();
}
inline ::google::protobuf::uint32 Awaken_CS_SkillOpen::bookitemid() const {
  return bookitemid_;
}
inline void Awaken_CS_SkillOpen::set_bookitemid(::google::protobuf::uint32 value) {
  set_has_bookitemid();
  bookitemid_ = value;
}

// -------------------------------------------------------------------

// Awaken_SC_SkillOpen

// required int32 ret = 1;
inline bool Awaken_SC_SkillOpen::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Awaken_SC_SkillOpen::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Awaken_SC_SkillOpen::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Awaken_SC_SkillOpen::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 Awaken_SC_SkillOpen::ret() const {
  return ret_;
}
inline void Awaken_SC_SkillOpen::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_awaken_2eproto__INCLUDED
