// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_welfare.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "db_welfare.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace message {

namespace {

const ::google::protobuf::Descriptor* WelfareInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  WelfareInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_db_5fwelfare_2eproto() {
  protobuf_AddDesc_db_5fwelfare_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "db_welfare.proto");
  GOOGLE_CHECK(file != NULL);
  WelfareInfo_descriptor_ = file->message_type(0);
  static const int WelfareInfo_offsets_[23] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, discount_gift_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, discount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, gift_list_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, sign_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, lottery_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, online_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, holiday_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, login_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, login_num_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, login_tick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, isfirstcharge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, diamondgift_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, isgrowthfund_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, isneedextra_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, recivedgrowthfundlist_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, recivedgrowthlevellist_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, firstcharge_tick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, dailychargeactiveid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, dailycharge_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, todaychargenum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, lastchargettick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, firstchargettick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, received_level_awards_),
  };
  WelfareInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      WelfareInfo_descriptor_,
      WelfareInfo::default_instance_,
      WelfareInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelfareInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(WelfareInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_db_5fwelfare_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    WelfareInfo_descriptor_, &WelfareInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_db_5fwelfare_2eproto() {
  delete WelfareInfo::default_instance_;
  delete WelfareInfo_reflection_;
}

void protobuf_AddDesc_db_5fwelfare_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::proto::message::protobuf_AddDesc_welfare_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020db_welfare.proto\022\rproto.message\032\rwelfa"
    "re.proto\"\240\006\n\013WelfareInfo\022\032\n\022discount_gif"
    "t_time\030\001 \001(\004\022\020\n\010discount\030\002 \001(\005\022.\n\tgift_l"
    "ist\030\003 \003(\0132\033.proto.message.DiscountItem\022*"
    "\n\tsign_data\030\004 \001(\0132\027.proto.message.SignDa"
    "ta\0220\n\014lottery_data\030\005 \001(\0132\032.proto.message"
    ".LotteryData\022.\n\013online_data\030\006 \001(\0132\031.prot"
    "o.message.OnlineData\0224\n\014holiday_data\030\007 \003"
    "(\0132\036.proto.message.SingleAwardData\0222\n\nlo"
    "gin_data\030\010 \003(\0132\036.proto.message.SingleAwa"
    "rdData\022\021\n\tlogin_num\030\t \001(\005\022\022\n\nlogin_tick\030"
    "\n \001(\r\022\025\n\risfirstcharge\030\013 \001(\005\0228\n\020diamondg"
    "ift_data\030\014 \003(\0132\036.proto.message.DiamondGi"
    "ftData\022\024\n\014isgrowthfund\030\r \001(\005\022\023\n\013isNeedEx"
    "tra\030\016 \001(\005\022\035\n\025recivedgrowthfundlist\030\017 \003(\005"
    "\022\036\n\026recivedgrowthlevellist\030\020 \003(\005\022\030\n\020firs"
    "tcharge_tick\030\021 \001(\r\022\033\n\023dailychargeActiveI"
    "d\030\022 \001(\005\0228\n\020dailycharge_data\030\023 \003(\0132\036.prot"
    "o.message.SingleAwardData\022\026\n\016todaycharge"
    "num\030\024 \001(\005\022\027\n\017lastChargettick\030\025 \001(\r\022\030\n\020fi"
    "rstChargettick\030\026 \001(\r\022\035\n\025received_level_a"
    "wards\030\027 \003(\rB\017\n\rproto.message", 868);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "db_welfare.proto", &protobuf_RegisterTypes);
  WelfareInfo::default_instance_ = new WelfareInfo();
  WelfareInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_db_5fwelfare_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_db_5fwelfare_2eproto {
  StaticDescriptorInitializer_db_5fwelfare_2eproto() {
    protobuf_AddDesc_db_5fwelfare_2eproto();
  }
} static_descriptor_initializer_db_5fwelfare_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int WelfareInfo::kDiscountGiftTimeFieldNumber;
const int WelfareInfo::kDiscountFieldNumber;
const int WelfareInfo::kGiftListFieldNumber;
const int WelfareInfo::kSignDataFieldNumber;
const int WelfareInfo::kLotteryDataFieldNumber;
const int WelfareInfo::kOnlineDataFieldNumber;
const int WelfareInfo::kHolidayDataFieldNumber;
const int WelfareInfo::kLoginDataFieldNumber;
const int WelfareInfo::kLoginNumFieldNumber;
const int WelfareInfo::kLoginTickFieldNumber;
const int WelfareInfo::kIsfirstchargeFieldNumber;
const int WelfareInfo::kDiamondgiftDataFieldNumber;
const int WelfareInfo::kIsgrowthfundFieldNumber;
const int WelfareInfo::kIsNeedExtraFieldNumber;
const int WelfareInfo::kRecivedgrowthfundlistFieldNumber;
const int WelfareInfo::kRecivedgrowthlevellistFieldNumber;
const int WelfareInfo::kFirstchargeTickFieldNumber;
const int WelfareInfo::kDailychargeActiveIdFieldNumber;
const int WelfareInfo::kDailychargeDataFieldNumber;
const int WelfareInfo::kTodaychargenumFieldNumber;
const int WelfareInfo::kLastChargettickFieldNumber;
const int WelfareInfo::kFirstChargettickFieldNumber;
const int WelfareInfo::kReceivedLevelAwardsFieldNumber;
#endif  // !_MSC_VER

WelfareInfo::WelfareInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void WelfareInfo::InitAsDefaultInstance() {
  sign_data_ = const_cast< ::proto::message::SignData*>(&::proto::message::SignData::default_instance());
  lottery_data_ = const_cast< ::proto::message::LotteryData*>(&::proto::message::LotteryData::default_instance());
  online_data_ = const_cast< ::proto::message::OnlineData*>(&::proto::message::OnlineData::default_instance());
}

WelfareInfo::WelfareInfo(const WelfareInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void WelfareInfo::SharedCtor() {
  _cached_size_ = 0;
  discount_gift_time_ = GOOGLE_ULONGLONG(0);
  discount_ = 0;
  sign_data_ = NULL;
  lottery_data_ = NULL;
  online_data_ = NULL;
  login_num_ = 0;
  login_tick_ = 0u;
  isfirstcharge_ = 0;
  isgrowthfund_ = 0;
  isneedextra_ = 0;
  firstcharge_tick_ = 0u;
  dailychargeactiveid_ = 0;
  todaychargenum_ = 0;
  lastchargettick_ = 0u;
  firstchargettick_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

WelfareInfo::~WelfareInfo() {
  SharedDtor();
}

void WelfareInfo::SharedDtor() {
  if (this != default_instance_) {
    delete sign_data_;
    delete lottery_data_;
    delete online_data_;
  }
}

void WelfareInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WelfareInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return WelfareInfo_descriptor_;
}

const WelfareInfo& WelfareInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_db_5fwelfare_2eproto();
  return *default_instance_;
}

WelfareInfo* WelfareInfo::default_instance_ = NULL;

WelfareInfo* WelfareInfo::New() const {
  return new WelfareInfo;
}

void WelfareInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    discount_gift_time_ = GOOGLE_ULONGLONG(0);
    discount_ = 0;
    if (has_sign_data()) {
      if (sign_data_ != NULL) sign_data_->::proto::message::SignData::Clear();
    }
    if (has_lottery_data()) {
      if (lottery_data_ != NULL) lottery_data_->::proto::message::LotteryData::Clear();
    }
    if (has_online_data()) {
      if (online_data_ != NULL) online_data_->::proto::message::OnlineData::Clear();
    }
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    login_num_ = 0;
    login_tick_ = 0u;
    isfirstcharge_ = 0;
    isgrowthfund_ = 0;
    isneedextra_ = 0;
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    firstcharge_tick_ = 0u;
    dailychargeactiveid_ = 0;
    todaychargenum_ = 0;
    lastchargettick_ = 0u;
    firstchargettick_ = 0u;
  }
  gift_list_.Clear();
  holiday_data_.Clear();
  login_data_.Clear();
  diamondgift_data_.Clear();
  recivedgrowthfundlist_.Clear();
  recivedgrowthlevellist_.Clear();
  dailycharge_data_.Clear();
  received_level_awards_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool WelfareInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 discount_gift_time = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &discount_gift_time_)));
          set_has_discount_gift_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_discount;
        break;
      }

      // optional int32 discount = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_discount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &discount_)));
          set_has_discount();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_gift_list;
        break;
      }

      // repeated .proto.message.DiscountItem gift_list = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_gift_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_gift_list()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_gift_list;
        if (input->ExpectTag(34)) goto parse_sign_data;
        break;
      }

      // optional .proto.message.SignData sign_data = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sign_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sign_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_lottery_data;
        break;
      }

      // optional .proto.message.LotteryData lottery_data = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_lottery_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_lottery_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_online_data;
        break;
      }

      // optional .proto.message.OnlineData online_data = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_online_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_online_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_holiday_data;
        break;
      }

      // repeated .proto.message.SingleAwardData holiday_data = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_holiday_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_holiday_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_holiday_data;
        if (input->ExpectTag(66)) goto parse_login_data;
        break;
      }

      // repeated .proto.message.SingleAwardData login_data = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_login_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_login_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_login_data;
        if (input->ExpectTag(72)) goto parse_login_num;
        break;
      }

      // optional int32 login_num = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_login_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &login_num_)));
          set_has_login_num();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_login_tick;
        break;
      }

      // optional uint32 login_tick = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_login_tick:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &login_tick_)));
          set_has_login_tick();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_isfirstcharge;
        break;
      }

      // optional int32 isfirstcharge = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isfirstcharge:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &isfirstcharge_)));
          set_has_isfirstcharge();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_diamondgift_data;
        break;
      }

      // repeated .proto.message.DiamondGiftData diamondgift_data = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_diamondgift_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_diamondgift_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_diamondgift_data;
        if (input->ExpectTag(104)) goto parse_isgrowthfund;
        break;
      }

      // optional int32 isgrowthfund = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isgrowthfund:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &isgrowthfund_)));
          set_has_isgrowthfund();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_isNeedExtra;
        break;
      }

      // optional int32 isNeedExtra = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isNeedExtra:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &isneedextra_)));
          set_has_isneedextra();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(120)) goto parse_recivedgrowthfundlist;
        break;
      }

      // repeated int32 recivedgrowthfundlist = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_recivedgrowthfundlist:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 120, input, this->mutable_recivedgrowthfundlist())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_recivedgrowthfundlist())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(120)) goto parse_recivedgrowthfundlist;
        if (input->ExpectTag(128)) goto parse_recivedgrowthlevellist;
        break;
      }

      // repeated int32 recivedgrowthlevellist = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_recivedgrowthlevellist:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 2, 128, input, this->mutable_recivedgrowthlevellist())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_recivedgrowthlevellist())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(128)) goto parse_recivedgrowthlevellist;
        if (input->ExpectTag(136)) goto parse_firstcharge_tick;
        break;
      }

      // optional uint32 firstcharge_tick = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_firstcharge_tick:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &firstcharge_tick_)));
          set_has_firstcharge_tick();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(144)) goto parse_dailychargeActiveId;
        break;
      }

      // optional int32 dailychargeActiveId = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_dailychargeActiveId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dailychargeactiveid_)));
          set_has_dailychargeactiveid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(154)) goto parse_dailycharge_data;
        break;
      }

      // repeated .proto.message.SingleAwardData dailycharge_data = 19;
      case 19: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dailycharge_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_dailycharge_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(154)) goto parse_dailycharge_data;
        if (input->ExpectTag(160)) goto parse_todaychargenum;
        break;
      }

      // optional int32 todaychargenum = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_todaychargenum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &todaychargenum_)));
          set_has_todaychargenum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(168)) goto parse_lastChargettick;
        break;
      }

      // optional uint32 lastChargettick = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_lastChargettick:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &lastchargettick_)));
          set_has_lastchargettick();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(176)) goto parse_firstChargettick;
        break;
      }

      // optional uint32 firstChargettick = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_firstChargettick:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &firstchargettick_)));
          set_has_firstchargettick();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(184)) goto parse_received_level_awards;
        break;
      }

      // repeated uint32 received_level_awards = 23;
      case 23: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_received_level_awards:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 2, 184, input, this->mutable_received_level_awards())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_received_level_awards())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(184)) goto parse_received_level_awards;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void WelfareInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint64 discount_gift_time = 1;
  if (has_discount_gift_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->discount_gift_time(), output);
  }

  // optional int32 discount = 2;
  if (has_discount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->discount(), output);
  }

  // repeated .proto.message.DiscountItem gift_list = 3;
  for (int i = 0; i < this->gift_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->gift_list(i), output);
  }

  // optional .proto.message.SignData sign_data = 4;
  if (has_sign_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->sign_data(), output);
  }

  // optional .proto.message.LotteryData lottery_data = 5;
  if (has_lottery_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->lottery_data(), output);
  }

  // optional .proto.message.OnlineData online_data = 6;
  if (has_online_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->online_data(), output);
  }

  // repeated .proto.message.SingleAwardData holiday_data = 7;
  for (int i = 0; i < this->holiday_data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->holiday_data(i), output);
  }

  // repeated .proto.message.SingleAwardData login_data = 8;
  for (int i = 0; i < this->login_data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, this->login_data(i), output);
  }

  // optional int32 login_num = 9;
  if (has_login_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->login_num(), output);
  }

  // optional uint32 login_tick = 10;
  if (has_login_tick()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->login_tick(), output);
  }

  // optional int32 isfirstcharge = 11;
  if (has_isfirstcharge()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->isfirstcharge(), output);
  }

  // repeated .proto.message.DiamondGiftData diamondgift_data = 12;
  for (int i = 0; i < this->diamondgift_data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->diamondgift_data(i), output);
  }

  // optional int32 isgrowthfund = 13;
  if (has_isgrowthfund()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->isgrowthfund(), output);
  }

  // optional int32 isNeedExtra = 14;
  if (has_isneedextra()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->isneedextra(), output);
  }

  // repeated int32 recivedgrowthfundlist = 15;
  for (int i = 0; i < this->recivedgrowthfundlist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      15, this->recivedgrowthfundlist(i), output);
  }

  // repeated int32 recivedgrowthlevellist = 16;
  for (int i = 0; i < this->recivedgrowthlevellist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      16, this->recivedgrowthlevellist(i), output);
  }

  // optional uint32 firstcharge_tick = 17;
  if (has_firstcharge_tick()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(17, this->firstcharge_tick(), output);
  }

  // optional int32 dailychargeActiveId = 18;
  if (has_dailychargeactiveid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(18, this->dailychargeactiveid(), output);
  }

  // repeated .proto.message.SingleAwardData dailycharge_data = 19;
  for (int i = 0; i < this->dailycharge_data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      19, this->dailycharge_data(i), output);
  }

  // optional int32 todaychargenum = 20;
  if (has_todaychargenum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(20, this->todaychargenum(), output);
  }

  // optional uint32 lastChargettick = 21;
  if (has_lastchargettick()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(21, this->lastchargettick(), output);
  }

  // optional uint32 firstChargettick = 22;
  if (has_firstchargettick()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(22, this->firstchargettick(), output);
  }

  // repeated uint32 received_level_awards = 23;
  for (int i = 0; i < this->received_level_awards_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      23, this->received_level_awards(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* WelfareInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint64 discount_gift_time = 1;
  if (has_discount_gift_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->discount_gift_time(), target);
  }

  // optional int32 discount = 2;
  if (has_discount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->discount(), target);
  }

  // repeated .proto.message.DiscountItem gift_list = 3;
  for (int i = 0; i < this->gift_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->gift_list(i), target);
  }

  // optional .proto.message.SignData sign_data = 4;
  if (has_sign_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->sign_data(), target);
  }

  // optional .proto.message.LotteryData lottery_data = 5;
  if (has_lottery_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->lottery_data(), target);
  }

  // optional .proto.message.OnlineData online_data = 6;
  if (has_online_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->online_data(), target);
  }

  // repeated .proto.message.SingleAwardData holiday_data = 7;
  for (int i = 0; i < this->holiday_data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->holiday_data(i), target);
  }

  // repeated .proto.message.SingleAwardData login_data = 8;
  for (int i = 0; i < this->login_data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, this->login_data(i), target);
  }

  // optional int32 login_num = 9;
  if (has_login_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->login_num(), target);
  }

  // optional uint32 login_tick = 10;
  if (has_login_tick()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->login_tick(), target);
  }

  // optional int32 isfirstcharge = 11;
  if (has_isfirstcharge()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->isfirstcharge(), target);
  }

  // repeated .proto.message.DiamondGiftData diamondgift_data = 12;
  for (int i = 0; i < this->diamondgift_data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, this->diamondgift_data(i), target);
  }

  // optional int32 isgrowthfund = 13;
  if (has_isgrowthfund()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->isgrowthfund(), target);
  }

  // optional int32 isNeedExtra = 14;
  if (has_isneedextra()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(14, this->isneedextra(), target);
  }

  // repeated int32 recivedgrowthfundlist = 15;
  for (int i = 0; i < this->recivedgrowthfundlist_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(15, this->recivedgrowthfundlist(i), target);
  }

  // repeated int32 recivedgrowthlevellist = 16;
  for (int i = 0; i < this->recivedgrowthlevellist_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(16, this->recivedgrowthlevellist(i), target);
  }

  // optional uint32 firstcharge_tick = 17;
  if (has_firstcharge_tick()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(17, this->firstcharge_tick(), target);
  }

  // optional int32 dailychargeActiveId = 18;
  if (has_dailychargeactiveid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(18, this->dailychargeactiveid(), target);
  }

  // repeated .proto.message.SingleAwardData dailycharge_data = 19;
  for (int i = 0; i < this->dailycharge_data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        19, this->dailycharge_data(i), target);
  }

  // optional int32 todaychargenum = 20;
  if (has_todaychargenum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(20, this->todaychargenum(), target);
  }

  // optional uint32 lastChargettick = 21;
  if (has_lastchargettick()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(21, this->lastchargettick(), target);
  }

  // optional uint32 firstChargettick = 22;
  if (has_firstchargettick()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(22, this->firstchargettick(), target);
  }

  // repeated uint32 received_level_awards = 23;
  for (int i = 0; i < this->received_level_awards_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(23, this->received_level_awards(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int WelfareInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint64 discount_gift_time = 1;
    if (has_discount_gift_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->discount_gift_time());
    }

    // optional int32 discount = 2;
    if (has_discount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->discount());
    }

    // optional .proto.message.SignData sign_data = 4;
    if (has_sign_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->sign_data());
    }

    // optional .proto.message.LotteryData lottery_data = 5;
    if (has_lottery_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->lottery_data());
    }

    // optional .proto.message.OnlineData online_data = 6;
    if (has_online_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->online_data());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional int32 login_num = 9;
    if (has_login_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->login_num());
    }

    // optional uint32 login_tick = 10;
    if (has_login_tick()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->login_tick());
    }

    // optional int32 isfirstcharge = 11;
    if (has_isfirstcharge()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->isfirstcharge());
    }

    // optional int32 isgrowthfund = 13;
    if (has_isgrowthfund()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->isgrowthfund());
    }

    // optional int32 isNeedExtra = 14;
    if (has_isneedextra()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->isneedextra());
    }

  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // optional uint32 firstcharge_tick = 17;
    if (has_firstcharge_tick()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->firstcharge_tick());
    }

    // optional int32 dailychargeActiveId = 18;
    if (has_dailychargeactiveid()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->dailychargeactiveid());
    }

    // optional int32 todaychargenum = 20;
    if (has_todaychargenum()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->todaychargenum());
    }

    // optional uint32 lastChargettick = 21;
    if (has_lastchargettick()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->lastchargettick());
    }

    // optional uint32 firstChargettick = 22;
    if (has_firstchargettick()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->firstchargettick());
    }

  }
  // repeated .proto.message.DiscountItem gift_list = 3;
  total_size += 1 * this->gift_list_size();
  for (int i = 0; i < this->gift_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->gift_list(i));
  }

  // repeated .proto.message.SingleAwardData holiday_data = 7;
  total_size += 1 * this->holiday_data_size();
  for (int i = 0; i < this->holiday_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->holiday_data(i));
  }

  // repeated .proto.message.SingleAwardData login_data = 8;
  total_size += 1 * this->login_data_size();
  for (int i = 0; i < this->login_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->login_data(i));
  }

  // repeated .proto.message.DiamondGiftData diamondgift_data = 12;
  total_size += 1 * this->diamondgift_data_size();
  for (int i = 0; i < this->diamondgift_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->diamondgift_data(i));
  }

  // repeated int32 recivedgrowthfundlist = 15;
  {
    int data_size = 0;
    for (int i = 0; i < this->recivedgrowthfundlist_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->recivedgrowthfundlist(i));
    }
    total_size += 1 * this->recivedgrowthfundlist_size() + data_size;
  }

  // repeated int32 recivedgrowthlevellist = 16;
  {
    int data_size = 0;
    for (int i = 0; i < this->recivedgrowthlevellist_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->recivedgrowthlevellist(i));
    }
    total_size += 2 * this->recivedgrowthlevellist_size() + data_size;
  }

  // repeated .proto.message.SingleAwardData dailycharge_data = 19;
  total_size += 2 * this->dailycharge_data_size();
  for (int i = 0; i < this->dailycharge_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->dailycharge_data(i));
  }

  // repeated uint32 received_level_awards = 23;
  {
    int data_size = 0;
    for (int i = 0; i < this->received_level_awards_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->received_level_awards(i));
    }
    total_size += 2 * this->received_level_awards_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WelfareInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const WelfareInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const WelfareInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void WelfareInfo::MergeFrom(const WelfareInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  gift_list_.MergeFrom(from.gift_list_);
  holiday_data_.MergeFrom(from.holiday_data_);
  login_data_.MergeFrom(from.login_data_);
  diamondgift_data_.MergeFrom(from.diamondgift_data_);
  recivedgrowthfundlist_.MergeFrom(from.recivedgrowthfundlist_);
  recivedgrowthlevellist_.MergeFrom(from.recivedgrowthlevellist_);
  dailycharge_data_.MergeFrom(from.dailycharge_data_);
  received_level_awards_.MergeFrom(from.received_level_awards_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_discount_gift_time()) {
      set_discount_gift_time(from.discount_gift_time());
    }
    if (from.has_discount()) {
      set_discount(from.discount());
    }
    if (from.has_sign_data()) {
      mutable_sign_data()->::proto::message::SignData::MergeFrom(from.sign_data());
    }
    if (from.has_lottery_data()) {
      mutable_lottery_data()->::proto::message::LotteryData::MergeFrom(from.lottery_data());
    }
    if (from.has_online_data()) {
      mutable_online_data()->::proto::message::OnlineData::MergeFrom(from.online_data());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_login_num()) {
      set_login_num(from.login_num());
    }
    if (from.has_login_tick()) {
      set_login_tick(from.login_tick());
    }
    if (from.has_isfirstcharge()) {
      set_isfirstcharge(from.isfirstcharge());
    }
    if (from.has_isgrowthfund()) {
      set_isgrowthfund(from.isgrowthfund());
    }
    if (from.has_isneedextra()) {
      set_isneedextra(from.isneedextra());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_firstcharge_tick()) {
      set_firstcharge_tick(from.firstcharge_tick());
    }
    if (from.has_dailychargeactiveid()) {
      set_dailychargeactiveid(from.dailychargeactiveid());
    }
    if (from.has_todaychargenum()) {
      set_todaychargenum(from.todaychargenum());
    }
    if (from.has_lastchargettick()) {
      set_lastchargettick(from.lastchargettick());
    }
    if (from.has_firstchargettick()) {
      set_firstchargettick(from.firstchargettick());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void WelfareInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WelfareInfo::CopyFrom(const WelfareInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WelfareInfo::IsInitialized() const {

  if (has_online_data()) {
    if (!this->online_data().IsInitialized()) return false;
  }
  for (int i = 0; i < holiday_data_size(); i++) {
    if (!this->holiday_data(i).IsInitialized()) return false;
  }
  for (int i = 0; i < login_data_size(); i++) {
    if (!this->login_data(i).IsInitialized()) return false;
  }
  for (int i = 0; i < diamondgift_data_size(); i++) {
    if (!this->diamondgift_data(i).IsInitialized()) return false;
  }
  for (int i = 0; i < dailycharge_data_size(); i++) {
    if (!this->dailycharge_data(i).IsInitialized()) return false;
  }
  return true;
}

void WelfareInfo::Swap(WelfareInfo* other) {
  if (other != this) {
    std::swap(discount_gift_time_, other->discount_gift_time_);
    std::swap(discount_, other->discount_);
    gift_list_.Swap(&other->gift_list_);
    std::swap(sign_data_, other->sign_data_);
    std::swap(lottery_data_, other->lottery_data_);
    std::swap(online_data_, other->online_data_);
    holiday_data_.Swap(&other->holiday_data_);
    login_data_.Swap(&other->login_data_);
    std::swap(login_num_, other->login_num_);
    std::swap(login_tick_, other->login_tick_);
    std::swap(isfirstcharge_, other->isfirstcharge_);
    diamondgift_data_.Swap(&other->diamondgift_data_);
    std::swap(isgrowthfund_, other->isgrowthfund_);
    std::swap(isneedextra_, other->isneedextra_);
    recivedgrowthfundlist_.Swap(&other->recivedgrowthfundlist_);
    recivedgrowthlevellist_.Swap(&other->recivedgrowthlevellist_);
    std::swap(firstcharge_tick_, other->firstcharge_tick_);
    std::swap(dailychargeactiveid_, other->dailychargeactiveid_);
    dailycharge_data_.Swap(&other->dailycharge_data_);
    std::swap(todaychargenum_, other->todaychargenum_);
    std::swap(lastchargettick_, other->lastchargettick_);
    std::swap(firstchargettick_, other->firstchargettick_);
    received_level_awards_.Swap(&other->received_level_awards_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata WelfareInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = WelfareInfo_descriptor_;
  metadata.reflection = WelfareInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace proto

// @@protoc_insertion_point(global_scope)
